# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/UPMchk/Curso2025-2026/blob/master/Assignment4/course_materials/notebooks/Task06.ipynb

**Task 06: Modifying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Create a new class named Researcher"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

# this task is validated in the next step
ontology = Namespace("http://oeg.fi.upm.es/def/people#")
person   = Namespace("http://oeg.fi.upm.es/resource/person/")

g.bind("ontology", ontology)
g.bind("person", person)

"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**

"""

# TO DO
Person = ontology.Person
Professor = ontology.Professor
AssociateProfessor = ontology.AssociateProfessor
InterimAssociateProfessor = ontology.InterimAssociateProfessor
FullProfessor = ontology.FullProfessor

# Declararlas como clases
for cls in [Person, Professor, AssociateProfessor, InterimAssociateProfessor, FullProfessor]:
    g.add((cls, RDF.type, RDFS.Class))

# Labels EXACTOS (sin lang; con xsd:string)
g.add((Person, RDFS.label, Literal("Person", datatype=XSD.string)))
g.add((Professor, RDFS.label, Literal("Professor", datatype=XSD.string)))
g.add((AssociateProfessor, RDFS.label, Literal("AssociateProfessor", datatype=XSD.string)))
g.add((InterimAssociateProfessor, RDFS.label, Literal("InterimAssociateProfessor", datatype=XSD.string)))
g.add((FullProfessor, RDFS.label, Literal("FullProfessor", datatype=XSD.string)))

# Jerarquía (subClassOf)
g.add((Professor, RDFS.subClassOf, Person))
g.add((AssociateProfessor, RDFS.subClassOf, Professor))
g.add((InterimAssociateProfessor, RDFS.subClassOf, AssociateProfessor))
g.add((FullProfessor, RDFS.subClassOf, Professor))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_01(g)

"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string)**"""

# TO DO
# Propiedades
hasColleague = ontology.hasColleague
hasName = ontology.hasName
hasHomePage = ontology.hasHomePage

# Declararlas como propiedades
for prop in [hasColleague, hasName, hasHomePage]:
    g.add((prop, RDF.type, RDF.Property))

# Labels EXACTOS (xsd:string)
g.add((hasColleague, RDFS.label, Literal("hasColleague", datatype=XSD.string)))
g.add((hasName, RDFS.label, Literal("hasName", datatype=XSD.string)))
g.add((hasHomePage, RDFS.label, Literal("hasHomePage", datatype=XSD.string)))

# Domain/Range según el diagrama
g.add((hasColleague, RDFS.domain, ontology.Person))
g.add((hasColleague, RDFS.range,  ontology.Person))

g.add((hasName, RDFS.domain, ontology.Person))
g.add((hasName, RDFS.range,  RDFS.Literal))

g.add((hasHomePage, RDFS.domain, ontology.FullProfessor))
g.add((hasHomePage, RDFS.range,  RDFS.Literal))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_02(g)

"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

# TO DO
# Individuos (en el prefijo person)
Oscar = person.Oscar
Asun  = person.Asun
Raul  = person.Raul

# Tipos
g.add((Oscar, RDF.type, ontology.Person))
g.add((Asun,  RDF.type, ontology.FullProfessor))
g.add((Raul,  RDF.type, ontology.Person))

# Labels (xsd:string)
g.add((Oscar, RDFS.label, Literal("Oscar", datatype=XSD.string)))
g.add((Asun,  RDFS.label, Literal("Asun",  datatype=XSD.string)))
g.add((Raul,  RDFS.label, Literal("Raul",  datatype=XSD.string)))

# Relaciones del diagrama (mínimas para validar)
g.add((Oscar, ontology.hasColleague, Asun))
g.add((Oscar, ontology.hasName, Literal("Oscar", datatype=XSD.string)))

g.add((Asun, ontology.hasHomePage, Literal("https://asun.example.org", datatype=XSD.string)))
g.add((Asun, ontology.hasColleague, Oscar))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

r.validate_task_06_03(g)

"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually**

"""

# TO DO
# Usar las propiedades del example4.rdf (defínelas "a mano")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
FOAF  = Namespace("http://xmlns.com/foaf/0.1/")

# (bind opcional; no afecta a la validación)
g.bind("vcard", VCARD)
g.bind("foaf", FOAF)

# Añadir a person:Oscar los datos pedidos
Oscar = person.Oscar  # por si ejecutas celdas sueltas
g.add((Oscar, VCARD.Given,  Literal("Oscar", datatype=XSD.string)))
g.add((Oscar, VCARD.Family, Literal("Garcia", datatype=XSD.string)))
g.add((Oscar, FOAF.email,   Literal("oscar@example.org", datatype=XSD.string)))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_04(g)
r.save_report("_Task_06")